## Article
addArticle:
    path: /bloggeur/add/article
    defaults: {_controller: AppBundle:Article:add}

addAjaxArticle:
    path: /bloggeur/addArticle/ajax/{article}
    defaults: {_controller: AppBundle:Article:addAjax}

listArticle:
    path: /bloggeur/list
    defaults: {_controller: AppBundle:Article:list}

publishArticle:
    path: /bloggeur/publishArticle/{article}
    defaults: {_controller: AppBundle:Article:publish}

editArticle:
    path: /bloggeur/editArticle/{article}
    defaults: {_controller: AppBundle:Article:editArticle}

deleteArticle:
    path: /bloggeur/deleteArticle/{article}
    defaults: {_controller: AppBundle:Article:deleteArticle}

showOneArticle:
    path: /article/{article}/
    defaults: {_controller: AppBundle:Article:OneArticle}

## Commentaire
addCommentaire:
    path: /article/{article}/comment
    defaults: {_controller: AppBundle:Commentaire:add}

deleteCommentaire:
    path: /bloggeur/delete/commentaire/{commentaire}
    defaults: {_controller: AppBundle:Commentaire:delete}

editCommentaire:
    path: /bloggeur/edit/commentaire/{commentaire}
    defaults: {_controller: AppBundle:Commentaire:edit}

## Image
addImage:
    path: /bloggeur/add/image
    defaults: {_controller: AppBundle:Image:addImage}


homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}