addArticle:
    path: /bloggeur/addArticle
    defaults: {_controller: AppBundle:Article:add}

addAjaxArticle:
    path: /bloggeur/addArticle/ajax/{article}
    defaults: {_controller: AppBundle:Article:addAjax}

listArticle:
    path: /bloggeur/list
    defaults: {_controller: AppBundle:Article:list}

publishArticle:
    path: /bloggeur/publishArticle/{article}
    defaults: {_controller: AppBundle:Article:publish}

addCommentaire:
    path: /article/{article}/comment
    defaults: {_controller: AppBundle:Commentaire:add}

showOneArticle:
    path: /article/{article}/
    defaults: {_controller: AppBundle:Article:OneArticle}

homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}