## Article
addArticle:
    path: /bloggeur/addArticle
    defaults: {_controller: AppBundle:Article:add}

addAjaxArticle:
    path: /bloggeur/addArticle/ajax/{article}
    defaults: {_controller: AppBundle:Article:addAjax}

listArticle:
    path: /bloggeur/list
    defaults: {_controller: AppBundle:Article:list}

publishArticle:
    path: /bloggeur/publishArticle/{article}
    defaults: {_controller: AppBundle:Article:publish}

editArticle:
    path: /bloggeur/editArticle/{article}
    defaults: {_controller: AppBundle:Article:editArticle}

deleteArticle:
    path: /bloggeur/deleteArticle/{article}
    defaults: {_controller: AppBundle:Article:deleteArticle}

## Commentaire
addCommentaire:
    path: /article/{article}/comment
    defaults: {_controller: AppBundle:Commentaire:add}

showOneArticle:
    path: /article/{article}/
    defaults: {_controller: AppBundle:Article:OneArticle}

deleteCommentaire:
    path: /bloggeur/delete/commentaire/{commentaire}
    defaults: {_controller: AppBundle:Commentaire:delete}

homepage:
    path: /
    defaults: {_controller: AppBundle:Default:index}